apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-backend
  namespace: parking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parking-backend
  template:
    metadata:
      labels:
        app: parking-backend
    spec:
      containers:
      - name: parking-backend
        image: ines234/parking-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "parking-db.ctcogso2uee6.us-east-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "MyStrongPass123!"
        - name: DB_NAME
          value: "parkingdb"
