apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-frontend
  namespace: parking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parking-frontend
  template:
    metadata:
      labels:
        app: parking-frontend
    spec:
      containers:
      - name: parking-frontend
        image: ines234/parking-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: "http://aba514ebae7b7407c8f5cb195f3dc64c-1293732178.us-east-1.elb.amazonaws.com:5000"

        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf

      volumes:
      - name: nginx-config
        configMap:
          name: frontend-nginx-config
          defaultMode: 420
